### ISSUE TITLE
Figure out how to get backups so chuck feels comfortable playing around

### ISSUE THREAD

**Issue by vosechu** [psas/rocket-table#8]

**Comment by natronics** [comment]
Lets do this: we need a CF card reader and some space ( >= 8 GB SD cards.)

```
$ dd if=/dev/CF of=/dev/SD BS=1M
```

A couple of times and label the SD cards and put them somewhere safe (FC box, probably).

**Comment by vosechu** [comment]
I have at least one SD card that could be donated. I also have a 128Gb external HD that I could donate if that could be helpful? What do you think?

**Comment by natronics** [comment]
Well, that would also work, but is overkill. I like SD cards in that they're self contained and small (of course that also means easy to lose). Also I think a lot of people have SD card slots on their laptops, which is convenient.

**Comment by vosechu** [comment]
Totally. I also didn't realize that they're only about $2 each. I assume we can use the cheapest crappiest ones possible?

http://www.amazon.com/s/ref=sr_nr_n_1?fst=as%3Aoff&rh=n%3A172282%2Cn%3A1197396%2Ck%3A8gb+sd+card&sort=price-asc-rank&keywords=8gb+sd+card&ie=UTF8&qid=1428342988&rnid=493964

**Comment by natronics** [comment]
Yep. Just backups, so don't care about speed (usually the deciding cost factor)

**Comment by vosechu** [comment]
Nope, I lied. Those are all $1 with $9 shipping. Tricksy!

**Comment by vosechu** [comment]
This seems to be the best price I could find for a Prime card - $5.66: http://www.amazon.com/SanDisk-Memory-Frustration-Free-Packaging--SDSDB-008G-AFFP/dp/B007JRB0TC/ref=sr_1_1?s=pc&ie=UTF8&qid=1428343581&sr=1-1&keywords=8gb+sd+card+-adapter

How many do we actually need?

**Comment by natronics** [comment]
oh, like, 3 is plenty. (two current redundant backups, and maybe one older one from the last launch or something)

**Comment by vosechu** [comment]
Oh killer. I'll order these now then. I don't mind a $15 outlay :)

**Comment by vosechu** [comment]
Ordered.
